Repository stackabletech/test-dev-cluster, pull requests merged in 2021-08, with the labels that each got.

#33 Add required cliArgs parameter to monitoring CR
  stackable-scripts/cr/monitoring-cluster.yaml
Labels: type/bug

#34 Add a note about systemd compatibility
  README.md
Labels: type/documentation, priority/medium

#36 Kafka now gets a zookeeper side car and not just monitoring.
  init.sh
Labels: type/bug, priority/medium

#37 Add license
  LICENSE
Labels: type/enhancement, priority/low
